version: '3'

services:
  db:
    image: postgres
    ports:
       - '5432'
    networks:
      some_network:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
    - SQL_ENGINE=django.db.backends.postgresql
    - SQL_DATABASE=postgres
    - SQL_USER=postgres
    - SQL_PASSWORD=postgres
    - SQL_HOST=db
    - SQL_PORT=5432
    - DATABASE=postgres
    - USE_S3=TRUE
    depends_on:
      - db
    links:
      - db:db
    networks:
      some_network:
  networks:
   some_network: